Web.User/Controllers/PartnerController.cs
using Common.Dtos;
using Common.Settings;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Web.User.Helpers;
using Web.User.Models;
using Web.User.Services;

namespace Web.User.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RoleTypeNames.Partner)]
    [Route("Partners")]
    public class PartnerController : Controller
    {
        private readonly PartnerService _partnerService;
        private readonly LookupsService _lookupsService;
        private readonly ViewHelper _viewHelper;
        private readonly string _profileImageFolder;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly FileHelper _fileHelper;
        private readonly Mapper _mapper;
        private readonly CacheHelper _cacheHelper;
        private readonly AppSettings _appSettings;

        public PartnerController(
            PartnerService partnerService, 
            LookupsService lookupsService,
            ViewHelper viewHelper,
            IWebHostEnvironment webHostEnvironment, 
            FileHelper fileHelper, 
            Mapper mapper,
            CacheHelper cacheHelper,
            IOptions<AppSettings> options)
        {
            _partnerService = partnerService;
            _lookupsService = lookupsService;
            _viewHelper = viewHelper;
            _webHostEnvironment = webHostEnvironment;
            _fileHelper = fileHelper;
            _mapper = mapper;
            _cacheHelper = cacheHelper;
            _appSettings = options.Value;
            _profileImageFolder = Path.Combine(_webHostEnvironment.ContentRootPath, "wwwroot", "images", "userprofiles");
        }

        private int GetOrganizationId()
        {
            string key = HttpContext.Session.GetString(Constants.LoggedInUserCachekey);
            var orgUser = _cacheHelper.Get<GetApplicationOrganizationResponseDto>(key);
            return orgUser.OrganizationId;
        }

        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            PartnerLandingModel model = new PartnerLandingModel();
            var orgId = GetOrganizationId();
            var userList = await _partnerService.GetOrganizationUserListAsync(orgId, _appSettings.Partners.MruListCount, _viewHelper.GetAccessToken(User), cancellationToken);
            if (userList.Success)
            {
                model.UserMruList = userList.Users;
            }
            
            return View(model);
        }

        [HttpGet("dashboard")]
        public async Task<IActionResult> Dashboard()
        {
            return View();
        }

        #region Groups
        [HttpGet("groups")]
        public async Task<IActionResult> Groups()
        {
            return View();
        }

        [HttpGet("group/{id}")]
        public async Task<IActionResult> Group(int id, CancellationToken cancellationToken)
        {
            ApplicationGroupModel model = new ApplicationGroupModel();
            var accessToken = _viewHelper.GetAccessToken(User);
            var result = await _lookupsService.GetGroupByIdAsync(id, accessToken, cancellationToken);
            if (result.Success)
            {
                _mapper.Map(result, model);
            }
            return View(model);
        }

        #endregion Groups

        [HttpGet("users")]
        public async Task<IActionResult> Users()
        {
            return View();
        }

        [HttpGet("adduser")]
        public async Task<IActionResult> AddUser(CancellationToken cancellationToken)
        {
            RegisterPartnerUserModel model = new RegisterPartnerUserModel();
            return View(model);
        }

        [HttpPost("adduser")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser(RegisterPartnerUserModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                string accessToken = _viewHelper.GetAccessToken(User);
                CreateOrganizationUserCommand command = new CreateOrganizationUserCommand();
                _mapper.Map(model, command);
                command.OrganizationId = GetOrganizationId();
                command.RoleId = (int)RoleTypes.PartnerUser;                
                var result = await _partnerService.CreateOrganizationUserAsync(command, accessToken, cancellationToken);
                if (result.Success)
                {
                    if (!string.IsNullOrEmpty(model.ImageData) && !string.IsNullOrEmpty(model.ImageFilename))
                    {
                        model.ImagePath = _fileHelper.UploadImage(model.ImageData, model.ImageFilename, result.UserGuid.ToString(), _profileImageFolder);
                    }

                    UpdateOrganizationUserProfileCommand updateCommand = new UpdateOrganizationUserProfileCommand();

                    _mapper.Map(model, updateCommand);
                    updateCommand.UserId = result.UserId;

                    var userDto = await _partnerService.UpdateOrganizationUserAsync(updateCommand, accessToken, cancellationToken);
                    if (!userDto.Success)
                    {
                        ModelState.AddModelError("", userDto?.Message ?? "Server error occured, please contact support");
                    }
                    else
                    {
                        return RedirectToAction("User", "Partners", new { id = result.UserGuid });
                    }
                }
                else
                {
                    ModelState.AddModelError("", result?.Message ?? "Server error occured, please contact support");
                }
            }
            return View(model);
        }

        [HttpGet("user/{userGuid}")]
        public async Task<IActionResult> GetUser(string userGuid, CancellationToken cancellationToken)
        {
            var accessToken = _viewHelper.GetAccessToken(User);
            var userDto = await _partnerService.GetOrganizationUserAsync(userGuid, accessToken, cancellationToken);
            PartnerUserProfileModel profileModel = new PartnerUserProfileModel();
            _mapper.Map(userDto, profileModel);
            if (!string.IsNullOrEmpty(profileModel.ImagePath) && !_fileHelper.IsProfileImageExists(profileModel.ImagePath, _profileImageFolder))
            {
                profileModel.ImagePath = Constants.DefaultProfileImage;
            }
            return View(profileModel);
        }

        [HttpPost("user/{userGuid}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostUser(PartnerUserProfileModel profileModel, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(profileModel.ImageData) && !string.IsNullOrEmpty(profileModel.ImageFilename))
                {
                    profileModel.ImagePath = _fileHelper.UploadImage(profileModel.ImageData, profileModel.ImageFilename, profileModel.UserGuid.ToString(), _profileImageFolder);
                }
                string accessToken = _viewHelper.GetAccessToken(User);

                UpdateOrganizationUserProfileCommand command = new UpdateOrganizationUserProfileCommand();

                _mapper.Map(profileModel, command);

                var userDto = await _partnerService.UpdateOrganizationUserAsync(command, accessToken, cancellationToken);
                if (userDto != null && userDto.Success)
                {
                    _mapper.Map(userDto, profileModel);                    
                }
                else
                {
                    ModelState.AddModelError("", userDto?.Message ?? "Server error occured, please contact support");
                }
            }
            return View("GetUser", profileModel);
        }
    }
}

Web.User/Views/Shared/_AdminLayout.cshtml
@inject Web.User.Helpers.ViewHelper viewHelper
@{
    bool isUserLoggedIn = viewHelper.IsLoggedIn(User);
    var roleType = viewHelper.GetUserRole(User);
    var activeLinkData = ViewData["ActiveLink"];
    string activeLink = "none";
    if(activeLinkData != null)
    {
        activeLink = activeLinkData?.ToString() ?? "none";
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/admin.site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.User.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="">
        <main class="d-flex min-vh-100">
            <aside class="navbar justify-content-start flex-column col-2 border-end align-items-start">
                <div class="branding d-flex px-4 col-12 pt-1 border-bottom">
                    <span>
                        <img id="map-icon" src="~/images/map_icon.svg" class="align-top me-2" />
                        <a class="navbar-brand text-wrap" asp-area="" asp-controller="Admin" asp-action="Index">GeoSense Admin</a>
                    </span>
                </div>
                <nav class="panel-menu d-block col-12 pt-2">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="Index" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Home")">
                                <i class="fa-solid fa-home d-inline-block col-1"></i><span class="col-9 ms-2">Home</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="Dashboard" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Dashboard")">
                                <i class="fa-solid fa-chart-line d-inline-block col-1"></i><span class="col-9 ms-2">Dashboard</span>
                            </a>
                        </li>
                    </ul>
                    <span class="ps-3 link-header">Management</span>
                    <ul class="nav flex-column pt-2">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Admin" asp-action="Partners" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Partners")">
                                <i class="fa-solid fa-briefcase d-inline-block col-1"></i><span class="col-9 ms-2">Partners</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Admin" asp-action="Groups" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Groups")">
                                <i class="fa-solid fa-user-group d-inline-block col-1"></i><span class="col-9 ms-2">Groups</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Admin" asp-action="Users" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Users")">
                                <i class="fa-solid fa-users d-inline-block col-1"></i><span class="col-9 ms-2">Users</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </aside>
            <section class="d-flex flex-column flex-nowrap col-10">
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container-fluid">
                            <div class="collapse d-sm-inline-flex justify-content-end ms-auto">
                                @if (isUserLoggedIn)
                                {
                                    <ul class="navbar-nav">
                                        <li class="nav-item">
                                            <a asp-controller="Admin" asp-action="Settings" class="btn" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Settings">
                                                <i class="fa-solid fa-gear"></i>
                                            </a>
                                        </li>
                                        <li class="nav-item pe-3">
                                            <span class="btn position-relative" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Settings">
                                                <span class="position-absolute d-inline badge rounded-pill bg-danger">
                                                    99+
                                                    <span class="visually-hidden">unread messages</span>
                                                </span>
                                                <i class="fa-solid fa-bell"></i>                                                
                                            </span>
                                        </li>                                        
                                    </ul>
                                    <div class="dropdown input-group">
                                        <label class="btn btn-outline-secondary">
                                            <i class="fa-solid fa-user"></i> @viewHelper.GetFullName(User, Context)
                                        </label>
                                        <a class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            <span class="visually-hidden">Toggle Dropdown</span>
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="profile"><i class="fa-solid fa-user-gear"></i> Profile</a></li>
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="changepassword"><i class="fa-solid fa-key"></i> Change Password</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="logout"><i class="fa-solid fa-power-off"></i> Logout</a></li>
                                        </ul>
                                    </div>
                                }
                                else
                                {
                                    if (viewHelper.ShouldShowLoginRegisterLinks(Context))
                                    {
                                        <ul class="navbar-nav">
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login"><i class="fa-solid fa-right-to-bracket"></i> Log In</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register"><i class="fa-solid fa-user-plus"></i> Register</a>
                                            </li>
                                        </ul>
                                    }
                                }
                            </div>
                        </div>
                    </nav>
                </header>
                <section>
                    <div>
                        <main role="main" class="pb-3">
                            <div class="container">
                                @RenderBody()
                            </div>
                        </main>
                    </div>
                </section>
                <footer class="mt-auto border-top footer text-muted">
                    <div class="container">
                        &copy; 2023 - Web.User - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                </footer>
            </section>
        </main>        
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web.User/Views/Shared/_PartnerLayout.cshtml
@inject Web.User.Helpers.ViewHelper viewHelper
@{
    bool isUserLoggedIn = viewHelper.IsLoggedIn(User);
    var roleType = viewHelper.GetUserRole(User);
    var activeLinkData = ViewData["ActiveLink"];
    string activeLink = "none";
    if (activeLinkData != null)
    {
        activeLink = activeLinkData?.ToString() ?? "none";
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/admin.site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.User.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="">
        <main class="d-flex min-vh-100">
            <aside class="navbar justify-content-start flex-column col-2 border-end align-items-start">
                <div class="branding d-flex px-4 col-12 pt-1 border-bottom">
                    <span>
                        <img id="map-icon" src="~/images/map_icon.svg" class="align-top me-2" />
                        <a class="navbar-brand text-wrap" asp-area="" asp-controller="Partners" asp-action="Index">GeoSense Partners</a>
                    </span>
                </div>
                <nav class="panel-menu d-block col-12 pt-2">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a asp-controller="Partners" asp-action="Index" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Home")">
                                <i class="fa-solid fa-home d-inline-block col-1"></i><span class="col-9 ms-2">Home</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Partners" asp-action="Dashboard" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Dashboard")">
                                <i class="fa-solid fa-chart-line d-inline-block col-1"></i><span class="col-9 ms-2">Dashboard</span>
                            </a>
                        </li>
                    </ul>
                    <span class="ps-3 link-header">Management</span>
                    <ul class="nav flex-column pt-2">                        
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Partners" asp-action="Groups" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Groups")">
                                <i class="fa-solid fa-user-group d-inline-block col-1"></i><span class="col-9 ms-2">Groups</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Partners" asp-action="Users" class="d-flex flex-row w-100 align-items-center ps-4 py-2 @viewHelper.GetActiveLink(activeLink, "Users")">
                                <i class="fa-solid fa-users d-inline-block col-1"></i><span class="col-9 ms-2">Users</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </aside>
            <section class="d-flex flex-column flex-nowrap col-10">
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container-fluid">
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                @await RenderSectionAsync("HeaderNavBar", required: false)
                            </div>
                            <div class="collapse d-sm-inline-flex justify-content-end ms-auto">
                                @if (isUserLoggedIn)
                                {
                                    <ul class="navbar-nav">
                                        <li class="nav-item">
                                            <a asp-controller="Partner" asp-action="Settings" class="btn" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Settings">
                                                <i class="fa-solid fa-gear"></i>
                                            </a>
                                        </li>
                                        <li class="nav-item pe-3">
                                            <span class="btn position-relative" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Settings">
                                                <span class="position-absolute d-inline badge rounded-pill bg-danger">
                                                    99+
                                                    <span class="visually-hidden">unread messages</span>
                                                </span>
                                                <i class="fa-solid fa-bell"></i>
                                            </span>
                                        </li>
                                    </ul>
                                    <div class="dropdown input-group">
                                        <label class="btn btn-outline-secondary">
                                            <i class="fa-solid fa-user"></i> @viewHelper.GetFullName(User, Context)
                                        </label>
                                        <a class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            <span class="visually-hidden">Toggle Dropdown</span>
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Partner" asp-action="profile"><i class="fa-solid fa-user-gear"></i> Profile</a></li>
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="changepassword"><i class="fa-solid fa-key"></i> Change Password</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="logout"><i class="fa-solid fa-power-off"></i> Logout</a></li>
                                        </ul>
                                    </div>
                                }
                                else
                                {
                                    if (viewHelper.ShouldShowLoginRegisterLinks(Context))
                                    {
                                        <ul class="navbar-nav">
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login"><i class="fa-solid fa-right-to-bracket"></i> Log In</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register"><i class="fa-solid fa-user-plus"></i> Register</a>
                                            </li>
                                        </ul>
                                    }
                                }
                            </div>
                        </div>
                    </nav>
                </header>
                <section>
                    <div>
                        <main role="main" class="pb-3">
                            <div class="container">
                                @RenderBody()
                            </div>
                        </main>
                    </div>
                </section>
                <footer class="mt-auto border-top footer text-muted">
                    <div class="container">
                        &copy; 2023 - Web.User - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                </footer>
            </section>
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>